apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 3
  selector:
    app: myjavaapp
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp  
    spec:
      containers:
        - name: myjavaapp-container
          image: sipu1996/myjenkinsimage
          ports:
            - containerPort: 8080
